sudo: required
language: generic
services:
    - docker

before_install:
    - docker build -t nvanbenschoten/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true nvanbenschoten/react-test yarn test

after_success:
    # Build docker images
    - docker build -t nvanbenschoten/multi-client ./client
    - docker build -t nvanbenschoten/multi-nginx ./nginx
    - docker build -t nvanbenschoten/multi-server ./server
    - docker build -t nvanbenschoten/multi-worker ./worker
    # Log in to the docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # Take those images and push them to docker hub
    - docker push nvanbenschoten/multi-client
    - docker push nvanbenschoten/multi-nginx
    - docker push nvanbenschoten/multi-server
    - docker push nvanbenschoten/multi-worker

deploy:
    provider: elasticbeanstalk
    region: 'us-east-1'
    app: 'multi-docker-prod'
    env: 'MultiDockerProd-env'
    bucket_name: 'elasticbeanstalk-us-east-1-048328650433'
    bucket_path: 'multi-docker-prod'
    on:
            branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
